# Options for analysis running.
issues: # https://golangci-lint.run/usage/configuration/#issues-configuration
  exclude:
    - github.com/kbinani/screenshot
  exclude-dirs:
    - Go2Me/go_base
    - Go2Me/go_struct
    - Go2Me/go_routine
    - Go2Me/go_runtime
    - Go2Me/go_robot
    - Go2Me/go_regexp
    - Go2Me/go_parse
    - Go2Me/go_sys
    - Go2Me/go_fatal_error
    - Go2Me/go_timer
    - Go2Me/go_reflect
    - libdemo/gencode
run: # https://golangci-lint.run/usage/configuration/#run-configuration
  # The default concurrency value is the number of available CPU.
#  concurrency: 4
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 1
  # Include test files or not.
  # Default: true
  tests: false
  # List of build tags, all linters use it.
  # Default: []
  build-tags:
    - tests
  # If set, we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  #
  # Allowed values: readonly|vendor|mod
  # Default: ""
  modules-download-mode: readonly
  # fix: buildir: failed to load package screenshot: could not load export data: no export data for "github.com/kbinani/screenshot"
  #modules-download-mode: vendor
  # Allow multiple parallel golangci-lint instances running.
  # If false, golangci-lint acquires file lock on start.
  # Default: false
  allow-parallel-runners: true
  # Allow multiple golangci-lint instances running, but serialize them around a lock.
  # If false, golangci-lint exits with an error if it fails to acquire file lock on start.
  # Default: false
  allow-serial-runners: true
  # Define the Go version limit.
  # Mainly related to generics support since go1.18.
  # Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.17
  # go: '1.19'