// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package demojson

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1267deecDecodeGithubComSinlovGoLangPlayGroundLibdemoDemojson(in *jlexer.Lexer, out *EBook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.BookId = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "author":
			out.Author = string(in.String())
		case "price":
			out.Price = float64(in.Float64())
		case "hot":
			out.Hot = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1267deecEncodeGithubComSinlovGoLangPlayGroundLibdemoDemojson(out *jwriter.Writer, in EBook) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.BookId))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix)
		out.String(string(in.Author))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"hot\":"
		out.RawString(prefix)
		out.Bool(bool(in.Hot))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EBook) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1267deecEncodeGithubComSinlovGoLangPlayGroundLibdemoDemojson(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EBook) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1267deecEncodeGithubComSinlovGoLangPlayGroundLibdemoDemojson(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EBook) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1267deecDecodeGithubComSinlovGoLangPlayGroundLibdemoDemojson(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EBook) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1267deecDecodeGithubComSinlovGoLangPlayGroundLibdemoDemojson(l, v)
}
