name: golang-codecov

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - 'main'
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10

permissions:
  contents: write

jobs:
  golang-codecov:
    name: golang-codecov
    strategy:
      matrix:
        go:
          - '^1.19'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go SDK
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Print env info
        run: |
          go env
          go version

      - name: Run go build
        run: go build -v -tags test ./...

      - name: Run test coverage
        run: go test -cover -tags test -coverprofile coverage.txt -covermode count -coverpkg ./... -v ./...

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: coverage.txt
#          verbose: true
